/* InstantOS self-host config.h for TinyCC 0.9.27.
 *
 * The upstream config.h is generated by ./configure; for the in-OS self-host we
 * ship this hand-written one so `tcc` (running on InstantOS) bakes the InstantOS
 * search paths into the tcc2 it produces. These mirror the NATIVE_DEFINES that
 * tools/build-tcc.sh passed on the command line when cross-building build/tcc:
 *   sysinclude : /lib/tcc/include (tcc builtins) : /include (ilibcxx) : /usr/include
 *   libpaths   : /lib/tcc : /lib : /usr/lib
 *   crtprefix  : /lib               (crt1.o/crti.o/crtn.o live here)
 *   elfinterp  : /lib/ld-instantos.so
 * tcc.h guards each with #ifndef, and includes config.h first, so these win.
 */
#ifndef CONFIG_TCCDIR
# define CONFIG_TCCDIR "/lib/tcc"
#endif
#define TCC_VERSION "0.9.27"
#define CONFIG_TCC_SYSINCLUDEPATHS "/lib/tcc/include:/include:/usr/include"
#define CONFIG_TCC_LIBPATHS "/lib/tcc:/lib:/usr/lib"
#define CONFIG_TCC_CRTPREFIX "/lib"
#define CONFIG_TCC_ELFINTERP "/lib/ld-instantos.so"
